# Generated by @flow-as-code/hcl from survey-module.flowdoc.json.
# Edits to structure regenerate; comments marked @keep survive.

resource "flowascode_contact_flow_module" "survey_module" {
  instance_id = var.connect_instance_id
  name        = "survey-module"

  refs = {
    "module:question@prod" = flowascode_contact_flow_module_alias.question_prod.arn
  }

  action {
    id   = "intro"
    next = "ask"
    message_participant {
      text = "One question."
    }
    error {
      type = "NoMatchingError"
      next = "wrap-up"
    }
  }

  action {
    id   = "ask"
    next = "wrap-up"
    invoke_flow_module {
      flow_module_id = flowascode_contact_flow_module_alias.question_prod.arn
    }
    error {
      type = "NoMatchingError"
      next = "wrap-up"
    }
  }

  action {
    id = "wrap-up"
    end_flow_module_execution {}
  }
}
