# Generated by @flow-as-code/hcl from doc.flowdoc.json.
# Edits to structure regenerate; comments marked @keep survive.

resource "flowascode_contact_flow" "flow_control" {
  instance_id = var.connect_instance_id
  name        = "flow-control"
  type        = "CONTACT_FLOW"
  description = "Flow-control actions, with a loop whose continue path is a back edge."

  refs = {
    "queue:front-desk" = aws_connect_queue.front_desk.arn
  }

  action {
    id   = "greet"
    next = "remember"
    message_participant {
      text = "Please hold while we look that up."
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
  }

  action {
    id   = "remember"
    next = "split"
    update_flow_attributes {
      flow_attributes = {
        lastPrompt = {
          value = "greet"
        }
      }
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
  }

  action {
    id   = "split"
    next = "bye"
    distribute_by_percentage {}
    condition {
      operator = "NumberLessThan"
      operands = ["31"]
      next     = "again"
    }
    condition {
      operator = "NumberLessThan"
      operands = ["51"]
      next     = "staffed"
    }
    error {
      type = "NoMatchingCondition"
      next = "bye"
    }
  }

  action {
    id   = "staffed"
    next = "bye"
    check_metric_data {
      metric_type = "NumberOfAgentsStaffed"
    }
    condition {
      operator = "NumberGreaterThan"
      operands = ["0"]
      next     = "load-metrics"
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
    error {
      type = "NoMatchingCondition"
      next = "wait-for-customer"
    }
  }

  action {
    id   = "load-metrics"
    next = "queue-depth"
    get_metric_data {
      queue_channel = "Voice"
      queue_id      = "queue:front-desk"
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
  }

  action {
    id   = "queue-depth"
    next = "bye"
    check_metric_data {
      metric_type = "NumberOfContactsInQueue"
      queue_id    = "queue:front-desk"
    }
    condition {
      operator = "NumberLessThan"
      operands = ["5"]
      next     = "load-agent-metrics"
    }
    condition {
      operator = "NumberGreaterOrEqualTo"
      operands = ["5"]
      next     = "bye"
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
    error {
      type = "NoMatchingCondition"
      next = "bye"
    }
  }

  action {
    id   = "load-agent-metrics"
    next = "wait-for-customer"
    get_metric_data {
      agent_id      = "$.Attributes.preferredAgentArn"
      queue_channel = "$.Channel"
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
  }

  action {
    id   = "again"
    next = "dynamic-loop"
    loop {
      loop_count = 2
    }
    condition {
      operator = "Equals"
      operands = ["ContinueLooping"]
      next     = "greet"
    }
    condition {
      operator = "Equals"
      operands = ["DoneLooping"]
      next     = "dynamic-loop"
    }
  }

  action {
    id   = "dynamic-loop"
    next = "wait-for-customer"
    loop {
      loop_count = "$.Attributes.retries"
    }
    condition {
      operator = "Equals"
      operands = ["ContinueLooping"]
      next     = "greet"
    }
    condition {
      operator = "Equals"
      operands = ["DoneLooping"]
      next     = "wait-for-customer"
    }
  }

  action {
    id   = "wait-for-customer"
    next = "bye"
    wait {
      events             = ["CustomerReturned", "BotParticipantDisconnected"]
      time_limit_seconds = 300
    }
    condition {
      operator = "Equals"
      operands = ["WaitCompleted"]
      next     = "wait-briefly"
    }
    condition {
      operator = "Equals"
      operands = ["CustomerReturned"]
      next     = "greet"
    }
    condition {
      operator = "Equals"
      operands = ["BotParticipantDisconnected"]
      next     = "bye"
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
    error {
      type = "ParticipantNotFound"
      next = "bye"
    }
  }

  action {
    id   = "wait-briefly"
    next = "bye"
    wait {
      time_limit_seconds = "$.Attributes.graceSeconds"
    }
    condition {
      operator = "Equals"
      operands = ["WaitCompleted"]
      next     = "bye"
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
  }

  action {
    id = "bye"
    disconnect_participant {}
  }
}
