# Generated by @flow-as-code/tf. Do not edit by hand: edit the
# FlowDoc and re-emit. See docs/03-tf-emitter.md.
#
# One entry per reference token in the emitted flow set, named
# <type>_<name>_arn with hyphens as underscores and the module alias
# folded in. Values are terraform addresses, never literal ARNs.

locals {
  flow_refs = {
    hours_main_line_arn = aws_connect_hours_of_operation.main_line.arn
    # TODO: no terraform address for ${cdref:lambda:appointment-lookup}.
    # Add one to the address map under key "lambda:appointment-lookup"
    # and re-emit. Until then this placeholder is an undeclared
    # reference, so `terraform validate` and `tofu validate` fail.
    lambda_appointment_lookup_arn = TODO_MISSING_ADDRESS_lambda_appointment_lookup
    # TODO: no terraform address for ${cdref:queue:appointments}.
    # Add one to the address map under key "queue:appointments"
    # and re-emit. Until then this placeholder is an undeclared
    # reference, so `terraform validate` and `tofu validate` fail.
    queue_appointments_arn = TODO_MISSING_ADDRESS_queue_appointments
  }
}
