# Generated by @flow-as-code/hcl from minimal.flowdoc.json.
# Edits to structure regenerate; comments marked @keep survive.

resource "flowascode_contact_flow" "minimal" {
  instance_id  = var.connect_instance_id
  name         = "minimal"
  display_name = null
  type         = "CONTACT_FLOW"
  description  = null
  start        = null
  state        = null
  settings     = null
  tags         = null

  refs = {
    "queue:appointments" = aws_connect_queue.appointments.arn
  }

  action {
    id   = "welcome"
    next = "set-queue"
    message_participant {
      text = "Welcome."
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
  }

  action {
    id   = "set-queue"
    next = "hang-up"
    update_contact_target_queue {
      queue_id = "queue:appointments"
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
  }

  action {
    id   = "hang-up"
    next = null
    disconnect_participant {}
  }
}
