# Generated by @flow-as-code/hcl from digit-queue.flowdoc.json.
# Edits to structure regenerate; comments marked @keep survive.

resource "flowascode_contact_flow" "digit_queue" {
  instance_id = var.connect_instance_id
  name        = "digit-queue"
  type        = "CONTACT_FLOW"

  action {
    id   = "set-queue"
    next = "hang-up"
    update_contact_target_queue {
      queue_id = aws_connect_queue._2fa.arn
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
  }

  action {
    id = "hang-up"
    disconnect_participant {}
  }
}
