# Generated by @flow-as-code/hcl from doc.flowdoc.json.
# Edits to structure regenerate; comments marked @keep survive.

resource "flowascode_contact_flow_module" "after_call_survey" {
  instance_id = var.connect_instance_id
  name        = "after-call-survey"

  refs = {
    "module:satisfaction-question@prod" = flowascode_contact_flow_module_alias.satisfaction_question_prod.arn
  }

  action {
    id   = "intro"
    next = "ask-question"
    message_participant {
      text = "Before you go, a one-question survey."
    }
    error {
      type = "NoMatchingError"
      next = "wrap-up"
    }
  }

  action {
    id   = "ask-question"
    next = "wrap-up"
    invoke_flow_module {
      flow_module_id = "module:satisfaction-question@prod"
    }
    error {
      type = "NoMatchingError"
      next = "wrap-up"
    }
  }

  action {
    id = "wrap-up"
    end_flow_module_execution {}
  }
}
