# Generated by @flow-as-code/hcl from doc.flowdoc.json.
# Edits to structure regenerate; comments marked @keep survive.

resource "flowascode_contact_flow" "regen_sample" {
  provider    = aws.west
  instance_id = var.connect_instance_id
  name        = "regen-sample"
  type        = "CONTACT_FLOW"
  state       = "ARCHIVED"

  refs = {
    "queue:appointments" = aws_connect_queue.appointments.arn
  }

  tags = {
    team = "cx"
  }

  lint {
    disable = ["prompt-length-3000"]
  }

  action {
    id   = "welcome"
    next = "set-queue"
    message_participant {
      text = "Welcome."
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
  }

  action {
    id   = "set-queue"
    next = "hang-up"
    update_contact_target_queue {
      queue_id = "queue:appointments"
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
  }

  action {
    id = "hang-up"
    disconnect_participant {}
  }

  lifecycle {
    prevent_destroy = true
  }

  depends_on = [aws_connect_queue.appointments]
}
