# Generated by @flow-as-code/hcl from doc.flowdoc.json.
# Edits to structure regenerate; comments marked @keep survive.

resource "flowascode_contact_flow" "contact_data" {
  instance_id = var.connect_instance_id
  name        = "contact-data"
  type        = "CONTACT_FLOW"
  description = "Contact-data actions: tags, voice, data and event hooks."

  refs = {
    "flow:queue-experience" = flowascode_contact_flow.queue_experience.arn
  }

  tags = {
    owner = "support"
    team  = "cx"
  }

  action {
    id   = "tag"
    next = "untag"
    tag_contact {
      tags = {
        team = "cx"
        tier = "$.Attributes.tier"
      }
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
  }

  action {
    id   = "untag"
    next = "set-voice"
    untag_contact {
      tag_keys = ["tier"]
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
  }

  action {
    id   = "set-voice"
    next = "set-voice-dynamic"
    update_contact_text_to_speech_voice {
      text_to_speech_engine = "Neural"
      text_to_speech_style  = "Conversational"
      text_to_speech_voice  = "Matthew"
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
  }

  action {
    id   = "set-voice-dynamic"
    next = "set-data"
    update_contact_text_to_speech_voice {
      text_to_speech_engine = "$.Attributes.engine"
      text_to_speech_voice  = "$.Attributes.voice"
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
  }

  action {
    id   = "set-data"
    next = "set-data-minimal"
    update_contact_data {
      customer_id                     = "c-1"
      description                     = "Priority caller"
      fraud_detection_threshold       = 50
      is_fraud_detection_enabled      = "FALSE"
      is_voice_authentication_enabled = "TRUE"
      is_voice_id_streaming_enabled   = "TRUE"
      language_code                   = "en-US"
      name                            = "$.Attributes.name"
      references = {
        CaseId = "$.Attributes.caseId"
      }
      target_contact                     = "Related"
      voice_authentication_response_time = 7
      voice_authentication_threshold     = 80
      watchlist_id                       = "a1B2c3D4e5F6g7H8i9J0kL"
      wisdom_session_arn                 = "$.Wisdom.SessionArn"
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
  }

  action {
    id   = "set-data-minimal"
    next = "set-queue-flow"
    update_contact_data {
      wisdom_session_arn = "$.Wisdom.SessionArn"
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
  }

  action {
    id   = "set-queue-flow"
    next = "set-whisper-flow"
    update_contact_event_hooks {
      event_hooks = {
        CustomerQueue = "$${cdref:flow:queue-experience}"
      }
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
  }

  action {
    id   = "set-whisper-flow"
    next = "greet"
    update_contact_event_hooks {
      event_hooks = {
        CustomerWhisper = "$.Attributes.whisperFlow"
      }
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
  }

  action {
    id   = "greet"
    next = "bye"
    message_participant {
      text = "Thanks for calling."
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
  }

  action {
    id = "bye"
    disconnect_participant {}
  }
}
