# Generated by @flow-as-code/hcl from hostile-text.flowdoc.json.
# Edits to structure regenerate; comments marked @keep survive.

resource "flowascode_contact_flow" "hostile_text" {
  instance_id = aws_connect_instance.main.id
  name        = "hostile-text"
  type        = "CONTACT_FLOW"

  refs = {
    "queue:appointments" = aws_connect_queue.appointments.arn
  }

  action {
    id   = "interpolation-lookalike"
    next = "directive-lookalike"
    message_participant {
      text = "Your balance is $${amount} and your next payment of $${due} is owed now."
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
  }

  action {
    id   = "directive-lookalike"
    next = "already-escaped"
    message_participant {
      text = "Template directives read %%{ if open } and %%{ for name in list }."
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
  }

  action {
    id   = "already-escaped"
    next = "sentinel-lookalike"
    message_participant {
      text = "Doubled already: $$${literal} and %%%{directive} stay exactly so."
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
  }

  action {
    id   = "sentinel-lookalike"
    next = "quotes-and-slashes"
    message_participant {
      text = "Sentinels CDREF_TF_SENTINEL_0_ and CDREF_TF_SENTINELX_0_ are caller text."
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
  }

  action {
    id   = "quotes-and-slashes"
    next = "set-queue"
    message_participant {
      text = "She said \"$${it is fine}\" and wrote C:\\temp\\%%{x} on the form."
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
  }

  action {
    id   = "set-queue"
    next = "hang-up"
    update_contact_target_queue {
      queue_id = "queue:appointments"
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
  }

  action {
    id = "hang-up"
    disconnect_participant {}
  }
}
