# Generated by @flow-as-code/tf. Do not edit by hand: edit the
# FlowDoc and re-emit. See docs/03-tf-emitter.md.
#
# Flow content is rendered from flows/<name>.flow.tftpl with the
# addresses in flow_refs.tf. Provider, credential, and backend
# configuration is yours; versions.tf.example lists what this needs.
#
# https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/connect_contact_flow
# https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/connect_contact_flow_module

resource "aws_connect_contact_flow" "hostile_text" {
  instance_id = aws_connect_instance.main.id
  name        = "hostile-text"
  type        = "CONTACT_FLOW"
  content     = templatefile("${path.module}/flows/hostile-text.flow.tftpl", local.flow_refs)
}
