# Generated by @flow-as-code/hcl. Do not edit by hand: edit the
# FlowDocs and re-emit. See docs/06-terraform-provider.md.
#
# One resource per FlowDoc, applied by the flow-as-code/flowascode
# provider. Provider, credential, and backend configuration is yours;
# versions.tf.example lists what this needs.

resource "flowascode_contact_flow_module" "satisfaction_question" {
  instance_id = var.connect_instance_id
  name        = "satisfaction-question"

  action {
    id   = "ask"
    next = "done"
    get_participant_input {
      input_time_limit_seconds = 5
      store_input              = "False"
      text                     = "Press 1 if we solved your problem, or 2 if we did not."
    }
    condition {
      operator = "Equals"
      operands = ["1"]
      next     = "done"
    }
    condition {
      operator = "Equals"
      operands = ["2"]
      next     = "done"
    }
    error {
      type = "InputTimeLimitExceeded"
      next = "done"
    }
    error {
      type = "NoMatchingCondition"
      next = "done"
    }
    error {
      type = "NoMatchingError"
      next = "done"
    }
  }

  action {
    id = "done"
    end_flow_module_execution {}
  }
}

# A snapshot of the module's content, replaced when the content
# changes, and the aliases it publishes: those the flows in this set
# invoke it through, and those declared to the emitter.
# Connect will not delete a version an alias points at, so the new
# version is created and the alias moved before the old one goes.
resource "flowascode_contact_flow_module_version" "satisfaction_question" {
  instance_id            = var.connect_instance_id
  contact_flow_module_id = flowascode_contact_flow_module.satisfaction_question.contact_flow_module_id
  content_hash           = flowascode_contact_flow_module.satisfaction_question.content_hash

  lifecycle {
    create_before_destroy = true
  }
}

resource "flowascode_contact_flow_module_alias" "satisfaction_question_live" {
  instance_id                 = var.connect_instance_id
  contact_flow_module_id      = flowascode_contact_flow_module.satisfaction_question.contact_flow_module_id
  name                        = "live"
  contact_flow_module_version = flowascode_contact_flow_module_version.satisfaction_question.version
}
