# Generated by @flow-as-code/hcl from appointment-line.flowdoc.json.
# Edits to structure regenerate; comments marked @keep survive.

resource "flowascode_contact_flow" "appointment_line" {
  instance_id = var.connect_instance_id
  name        = "appointment-line"
  type        = "CONTACT_FLOW"

  refs = {
    "hours:main-line"           = aws_connect_hours_of_operation.main_line.arn
    "lambda:appointment-lookup" = data.aws_lambda_function.appointment_lookup.arn
    "queue:appointments"        = aws_connect_queue.appointments.arn
  }

  action {
    id   = "enable-logging"
    next = "welcome"
    update_flow_logging_behavior {
      flow_logging_behavior = "Enabled"
    }
  }

  action {
    id   = "welcome"
    next = "check-hours"
    message_participant {
      text = "Thanks for calling. Let's get you to the right place."
    }
    error {
      type = "NoMatchingError"
      next = "apologize"
    }
  }

  action {
    id   = "check-hours"
    next = "announce-closed"
    check_hours_of_operation {
      hours_of_operation_id = "hours:main-line"
    }
    condition {
      operator = "Equals"
      operands = ["True"]
      next     = "set-working-queue"
    }
    condition {
      operator = "Equals"
      operands = ["False"]
      next     = "announce-closed"
    }
    error {
      type = "NoMatchingError"
      next = "apologize"
    }
  }

  action {
    id   = "set-working-queue"
    next = "look-up-appointment"
    update_contact_target_queue {
      queue_id = "queue:appointments"
    }
    error {
      type = "NoMatchingError"
      next = "apologize"
    }
  }

  action {
    id   = "look-up-appointment"
    next = "record-lookup-result"
    invoke_lambda_function {
      invocation_time_limit_seconds = 8
      invocation_type               = "SYNCHRONOUS"
      lambda_function_arn           = "lambda:appointment-lookup"
      response_validation = {
        response_type = "STRING_MAP"
      }
    }
    error {
      type = "NoMatchingError"
      next = "transfer"
    }
  }

  action {
    id   = "record-lookup-result"
    next = "transfer"
    update_contact_attributes {
      attributes = {
        appointmentFound = "$.External.appointmentFound"
      }
      target_contact = "Current"
    }
    error {
      type = "NoMatchingError"
      next = "transfer"
    }
  }

  action {
    id   = "transfer"
    next = "hang-up"
    transfer_contact_to_queue {}
    error {
      type = "QueueAtCapacity"
      next = "announce-busy"
    }
    error {
      type = "NoMatchingError"
      next = "apologize"
    }
  }

  action {
    id   = "announce-closed"
    next = "hang-up"
    message_participant {
      text = "We are closed right now. Please call back during business hours."
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
  }

  action {
    id   = "announce-busy"
    next = "hang-up"
    message_participant {
      text = "All of our lines are busy. Please try again shortly."
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
  }

  action {
    id   = "apologize"
    next = "hang-up"
    message_participant {
      text = "Something went wrong on our end. Please try again later."
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
  }

  action {
    id = "hang-up"
    disconnect_participant {}
  }
}
