# Generated by @flow-as-code/hcl. Do not edit by hand: edit the
# FlowDocs and re-emit. See docs/06-terraform-provider.md.
#
# Two outputs per document, named by its FlowDoc name: the ARN, and the
# SHA-256 of the document with its references still tokens, equal across
# environments that apply the same document and known at plan time. A
# promotion gate compares the hash one environment applied with the one
# the next plans (docs/tutorials/02-promote.md). A module that publishes
# aliases adds the ARN of each, the value a flow binds for module:<name>@<alias>.

output "appointment_line_arn" {
  description = "ARN of flow appointment-line."
  value       = flowascode_contact_flow.appointment_line.arn
}

output "appointment_line_document_sha256" {
  description = "SHA-256 of flow appointment-line as a FlowDoc, references still tokens: equal across environments that apply the same document."
  value       = sha256(flowascode_contact_flow.appointment_line.flowdoc)
}
