# Generated by @flow-as-code/hcl from doc.flowdoc.json.
# Edits to structure regenerate; comments marked @keep survive.

resource "flowascode_contact_flow" "dtmf_menu" {
  instance_id = var.connect_instance_id
  name        = "dtmf-menu"
  type        = "CONTACT_FLOW"

  refs = {
    # TODO: no terraform address for ${cdref:prompt:sales-confirm}.
    "prompt:sales-confirm" = null
  }

  lint {
    disable = ["prompt-length-3000"]
  }

  action {
    id   = "menu"
    next = "no-match"
    get_participant_input {
      input_time_limit_seconds = 5
      store_input              = "False"
      text                     = "For sales, press 1. For support, press 2. To hear this again, press star."
    }
    condition {
      operator = "Equals"
      operands = ["1"]
      next     = "sales"
    }
    condition {
      operator = "Equals"
      operands = ["2"]
      next     = "support"
    }
    condition {
      operator = "Equals"
      operands = ["*"]
      next     = "menu"
    }
    error {
      type = "InputTimeLimitExceeded"
      next = "timeout-notice"
    }
    error {
      type = "NoMatchingCondition"
      next = "no-match"
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
  }

  action {
    id   = "timeout-notice"
    next = "menu"
    message_participant {
      text = "We did not hear a selection."
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
  }

  action {
    id   = "no-match"
    next = "menu"
    message_participant {
      text = "That is not a valid option."
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
  }

  action {
    id   = "sales"
    next = "menu"
    get_participant_input {
      input_time_limit_seconds = 10
      prompt_id                = "prompt:sales-confirm"
      store_input              = "False"
    }
    condition {
      operator = "Equals"
      operands = ["1"]
      next     = "sales-transfer"
    }
    error {
      type = "InputTimeLimitExceeded"
      next = "menu"
    }
    error {
      type = "NoMatchingCondition"
      next = "menu"
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
  }

  action {
    id   = "sales-transfer"
    next = "bye"
    message_participant {
      text = "Connecting you to sales."
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
  }

  action {
    id   = "support"
    next = "support-transfer"
    get_participant_input {
      input_time_limit_seconds = 30
      ssml                     = "<speak>Press any key when you have your account number ready.</speak>"
      store_input              = "False"
    }
    error {
      type = "InputTimeLimitExceeded"
      next = "support-transfer"
    }
    error {
      type = "NoMatchingCondition"
      next = "support-transfer"
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
  }

  action {
    id   = "support-transfer"
    next = "bye"
    message_participant {
      text = "Connecting you to support."
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
  }

  action {
    id = "bye"
    disconnect_participant {}
  }
}
