# Generated by @flow-as-code/hcl from doc.flowdoc.json.
# Edits to structure regenerate; comments marked @keep survive.

resource "flowascode_contact_flow" "unknown_actions" {
  instance_id = var.connect_instance_id
  name        = "unknown-actions"
  type        = "CONTACT_FLOW"

  refs = {
    "flow:task-flow" = flowascode_contact_flow.task_flow.arn
    "queue:support"  = aws_connect_queue.support.arn
  }

  action {
    id   = "create-task"
    next = "resume-participant"
    generic {
      type = "CreateTask"
      parameters = jsonencode({
        Attributes = {
          CustomerPhoneNumber = "$.CustomerEndpoint.Address"
          queue               = "$${cdref:queue:support}"
        }
        ContactFlowId = "$${cdref:flow:task-flow}"
        Description   = "A task for the agent, with the customer's number."
        Name          = "Follow up"
      })
    }
    error {
      type = "NoMatchingError"
      next = "hand-off"
    }
  }

  action {
    id   = "resume-participant"
    next = "transfer-third-party"
    generic {
      type = "UpdatePreviousContactParticipantState"
      parameters = jsonencode({
        PreviousContactParticipantState = "OffHold"
      })
    }
    error {
      type = "NoMatchingError"
      next = "hand-off"
    }
  }

  action {
    id   = "transfer-third-party"
    next = "hand-off"
    generic {
      type = "TransferParticipantToThirdParty"
      parameters = jsonencode({
        ContinueFlowExecution                = "True"
        ThirdPartyConnectionTimeLimitSeconds = "30"
        ThirdPartyPhoneNumber                = "$.Attributes.deskPhone"
      })
    }
    error {
      type = "CallFailed"
      next = "hand-off"
    }
    error {
      type = "ConnectionTimeLimitExceeded"
      next = "hand-off"
    }
    error {
      type = "NoMatchingError"
      next = "hand-off"
    }
  }

  action {
    id = "hand-off"
    generic {
      type = "ResumeContact"
    }
  }
}
