# Generated by @flow-as-code/hcl from doc.flowdoc.json.
# Edits to structure regenerate; comments marked @keep survive.

resource "flowascode_contact_flow" "recording_analytics" {
  instance_id = var.connect_instance_id
  name        = "recording-analytics"
  type        = "CONTACT_FLOW"
  description = "The recording block in each of its forms, one per block, announced first."

  action {
    id   = "announce"
    next = "record-voice-ivr"
    message_participant {
      text = "This conversation may be recorded."
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
  }

  action {
    id   = "record-voice-ivr"
    next = "record-voice"
    update_contact_recording_and_analytics_behavior {
      voice_behavior = {
        voice_recording_behavior = {
          ivr_recording_behavior = "Enabled"
          recorded_participants  = ["Agent", "Customer"]
        }
      }
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
    error {
      type = "ChannelMismatch"
      next = "record-chat"
    }
  }

  action {
    id   = "record-voice"
    next = "record-screen"
    update_contact_recording_and_analytics_behavior {
      voice_behavior = {
        voice_recording_behavior = {
          recorded_participants = ["Customer"]
        }
      }
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
    error {
      type = "ChannelMismatch"
      next = "bye"
    }
  }

  action {
    id   = "record-screen"
    next = "bye"
    update_contact_recording_and_analytics_behavior {
      screen_recording_behavior = {
        screen_recorded_participants = ["Agent"]
      }
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
    error {
      type = "ChannelMismatch"
      next = "bye"
    }
  }

  action {
    id   = "record-chat"
    next = "bye"
    update_contact_recording_and_analytics_behavior {
      chat_behavior = jsonencode({
        ChatAnalyticsBehavior = {
          AnalyticsLanguage = "en-US"
          AnalyticsModes    = ["ContactLens"]
          Enabled           = "True"
          InFlightChatRedactionConfiguration = {
            DeliverUnprocessedMessages = "False"
            Enabled                    = "True"
            RedactionEntities          = ["CREDIT_DEBIT_NUMBER", "SSN"]
            RedactionMaskMode          = "PII"
          }
        }
      })
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
    error {
      type = "ChannelMismatch"
      next = "bye"
    }
    error {
      type = "InFlightRedactionConfigurationFailed"
      next = "bye"
    }
  }

  action {
    id = "bye"
    disconnect_participant {}
  }
}
