# Generated by @flow-as-code/tf. Do not edit by hand: edit the
# FlowDoc and re-emit. See docs/03-tf-emitter.md.
#
# One entry per reference token in the emitted flow set, named
# <type>_<name>_arn with hyphens as underscores and the module alias
# folded in. Values are terraform addresses, never literal ARNs.

locals {
  flow_refs = {
    hours_main_line_arn           = aws_connect_hours_of_operation.main_line.arn
    lambda_appointment_lookup_arn = data.aws_lambda_function.appointment_lookup.arn
    queue_appointments_arn        = aws_connect_queue.appointments.arn
  }
}
