# Generated by @flow-as-code/tf. Do not edit by hand: edit the
# FlowDoc and re-emit. See docs/03-tf-emitter.md.
#
# One entry per reference token in the emitted flow set, named
# <type>_<name>_arn with hyphens as underscores and the module alias
# folded in. Values are terraform addresses, never literal ARNs.

locals {
  flow_refs = {
    queue_appointments_arn = aws_connect_queue.appointments.arn
  }

  # after-call-survey references a resource this set emits. Its addresses
  # go in a local of their own: in the shared map they would make
  # that map depend on resources rendered from it, which both tools
  # report as a dependency cycle.
  module_refs_after_call_survey = merge(local.flow_refs, {
    module_satisfaction_question_prod_arn = awscc_connect_contact_flow_module_alias.satisfaction_question_prod.contact_flow_module_alias_arn
  })

  # support-line references a resource this set emits. Its addresses
  # go in a local of their own: in the shared map they would make
  # that map depend on resources rendered from it, which both tools
  # report as a dependency cycle.
  flow_refs_support_line = merge(local.flow_refs, {
    # Address map entry "module:after-call-survey@prod" ignored: this set emits
    # the resource itself, so the reference resolves to it.
    module_after_call_survey_prod_arn = awscc_connect_contact_flow_module_alias.after_call_survey_prod.contact_flow_module_alias_arn
  })
}
