# Generated by @flow-as-code/tf. Do not edit by hand: edit the
# FlowDoc and re-emit. See docs/03-tf-emitter.md.
#
# Flow content is rendered from flows/<name>.flow.tftpl with the
# addresses in flow_refs.tf. Provider, credential, and backend
# configuration is yours; versions.tf.example lists what this needs.
#
# https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/connect_contact_flow
# https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/connect_contact_flow_module
#
# Modules carry versions and aliases; full flows do not.
# CreateContactFlowVersion "only supports creating versions for
# flows of type Campaign", so a flow updates its content in place
# while a module pins content behind an alias.
# https://docs.aws.amazon.com/connect/latest/APIReference/API_CreateContactFlowVersion.html

resource "aws_connect_contact_flow_module" "after_call_survey" {
  instance_id = var.connect_instance_id
  name        = "after-call-survey"
  content     = templatefile("${path.module}/flows/after-call-survey.flow.tftpl", local.module_refs_after_call_survey)
}

# Snapshot of the module content as it stands when this resource is
# created. Replace it after a content change so the aliases below
# serve the new content.
# https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/connect_contact_flow_module_version
resource "awscc_connect_contact_flow_module_version" "after_call_survey" {
  contact_flow_module_id = aws_connect_contact_flow_module.after_call_survey.arn
}

# https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/connect_contact_flow_module_alias
resource "awscc_connect_contact_flow_module_alias" "after_call_survey_prod" {
  contact_flow_module_id      = aws_connect_contact_flow_module.after_call_survey.arn
  contact_flow_module_version = awscc_connect_contact_flow_module_version.after_call_survey.version
  name                        = "prod"
}

resource "aws_connect_contact_flow_module" "satisfaction_question" {
  instance_id = var.connect_instance_id
  name        = "satisfaction-question"
  content     = templatefile("${path.module}/flows/satisfaction-question.flow.tftpl", local.flow_refs)
}

# Snapshot of the module content as it stands when this resource is
# created. Replace it after a content change so the aliases below
# serve the new content.
# https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/connect_contact_flow_module_version
resource "awscc_connect_contact_flow_module_version" "satisfaction_question" {
  contact_flow_module_id = aws_connect_contact_flow_module.satisfaction_question.arn
}

# https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/connect_contact_flow_module_alias
resource "awscc_connect_contact_flow_module_alias" "satisfaction_question_prod" {
  contact_flow_module_id      = aws_connect_contact_flow_module.satisfaction_question.arn
  contact_flow_module_version = awscc_connect_contact_flow_module_version.satisfaction_question.version
  name                        = "prod"
}

resource "aws_connect_contact_flow" "support_line" {
  instance_id = var.connect_instance_id
  name        = "support-line"
  type        = "CONTACT_FLOW"
  content     = templatefile("${path.module}/flows/support-line.flow.tftpl", local.flow_refs_support_line)
}
