# Generated by @flow-as-code/tf. Do not edit by hand: edit the
# FlowDoc and re-emit. See docs/03-tf-emitter.md.

variable "connect_instance_id" {
  description = "Identifier of the Amazon Connect instance that holds these flows."
  type        = string
}
