// Generated by @flow-as-code/core codegen from survey-line.flowdoc.json.
// Edits to structure regenerate; comments marked @keep survive.

import {
  DisconnectParticipant,
  Flow,
  GenericBlock,
  InvokeFlowModule,
  Refs,
} from "@flow-as-code/core";

export function surveyLine(): Flow {
  return new Flow({
    name: "survey-line",
    displayName: "Survey line",
    connectType: "CONTACT_FLOW",
  }).add(
    new InvokeFlowModule({
      id: "prod",
      module: Refs.module("survey", "prod"),
      next: "pinned",
      onError: "bye",
    }),
    new InvokeFlowModule({
      id: "pinned",
      module: Refs.module("survey", "1"),
      next: "latest",
      onError: "bye",
    }),
    new GenericBlock({
      id: "latest",
      type: "InvokeFlowModule",
      parameters: { FlowModuleId: "${cdref:module:survey}" },
      next: "bye",
      errors: [{ errorType: "NoMatchingError", target: "bye" }],
    }),
    new DisconnectParticipant({ id: "bye" }),
  );
}
