// Generated by @flow-as-code/core codegen from survey.flowdoc.json.
// Edits to structure regenerate; comments marked @keep survive.

import { EndFlowModuleExecution, FlowModule } from "@flow-as-code/core";

export function survey(): FlowModule {
  return new FlowModule({
    name: "survey",
    displayName: "Survey",
    settings: { InputParameters: [], OutputParameters: [], Transitions: [] },
  }).add(new EndFlowModuleExecution({ id: "end" }));
}
