// Generated by @flow-as-code/core codegen from sample-after-contact-work-flow.flowdoc.json.
// Edits to structure regenerate; comments marked @keep survive.

import { DisconnectParticipant, Flow, GenericBlock } from "@flow-as-code/core";

export function sampleAfterContactWorkFlow(): Flow {
  return new Flow({
    name: "sample-after-contact-work-flow",
    displayName: "Sample after contact work flow",
    connectType: "CONTACT_FLOW",
  }).add(
    new GenericBlock({
      id: "wrap-up",
      type: "ShowView",
      parameters: {
        InvocationTimeLimitSeconds: "480",
        ViewData: { CustomerName: "Jane Doe" },
        ViewResource: { Id: "${cdref:view:after-contact-work@1}" },
      },
      next: "hang-up",
      errors: [
        { errorType: "NoMatchingError", target: "hang-up" },
        { errorType: "TimeLimitExceeded", target: "hang-up" },
      ],
      conditions: [{ target: "hang-up", operator: "Equals", operands: ["Done"] }],
    }),
    new DisconnectParticipant({ id: "hang-up" }),
  );
}
