# Generated by @flow-as-code/hcl from doc.flowdoc.json.
# Edits to structure regenerate; comments marked @keep survive.

resource "flowascode_contact_flow" "main_line" {
  instance_id  = var.connect_instance_id
  name         = "main-line"
  display_name = "Main Line \"After Hours\" (général)"
  type         = "CONTACT_FLOW"
  description  = "Adopted from the console with its name kept."

  action {
    id   = "closed"
    next = "bye"
    message_participant {
      text = "We are closed."
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
  }

  action {
    id = "bye"
    disconnect_participant {}
  }
}
