# Generated by @flow-as-code/hcl from doc.flowdoc.json.
# Edits to structure regenerate; comments marked @keep survive.

resource "flowascode_contact_flow" "regen_sample" {
  instance_id = var.connect_instance_id
  name        = "regen-sample"
  type        = "CONTACT_FLOW"

  refs = {
    # TODO: no terraform address for ${cdref:lambda:lookup}.
    "lambda:lookup"      = null
    "queue:appointments" = aws_connect_queue.appointments.arn
  }

  action {
    id   = "welcome"
    next = "look-up"
    message_participant {
      text = "Welcome."
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
  }

  action {
    id   = "look-up"
    next = "set-queue"
    invoke_lambda_function {
      invocation_time_limit_seconds = 8
      invocation_type               = "SYNCHRONOUS"
      lambda_function_arn           = "lambda:lookup"
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
  }

  action {
    id   = "set-queue"
    next = "hang-up"
    update_contact_target_queue {
      queue_id = "queue:appointments"
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
  }

  action {
    id = "hang-up"
    disconnect_participant {}
  }
}
