# Generated by @flow-as-code/hcl from doc.flowdoc.json.
# Edits to structure regenerate; comments marked @keep survive.

resource "flowascode_contact_flow" "edge_cases" {
  instance_id = var.connect_instance_id
  name        = "edge-cases"
  type        = "CONTACT_FLOW"
  description = "Every shape the builder can express and one it cannot."
  start       = "ssml-greeting"

  refs = {
    "prompt:welcome-prompt" = data.aws_connect_prompt.welcome_prompt.arn
  }

  action {
    id   = "odd-message"
    next = "hang-up"
    generic {
      type = "MessageParticipant"
      parameters = jsonencode({
        Text      = "You reached the odd path."
        Unmodeled = "true"
      })
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
    position {
      x = 40
      y = 320
    }
  }

  action {
    id   = "ssml-greeting"
    next = "compare-tier"
    message_participant {
      ssml = "<speak>Welcome to <emphasis level=\"strong\">the appointment line</emphasis>.</speak>"
    }
    error {
      type = "NoMatchingError"
      next = "prompt-fallback"
    }
    position {
      x = 40
      y = 40
    }
  }

  action {
    id   = "compare-tier"
    next = "odd-message"
    compare {
      comparison_value = "$.Attributes.tier"
    }
    condition {
      operator = "Equals"
      operands = ["gold"]
      next     = "prompt-fallback"
    }
    condition {
      operator = "NumberGreaterThan"
      operands = ["3"]
      next     = "queue-by-attribute"
    }
    error {
      type = "NoMatchingCondition"
      next = "odd-message"
    }
    position {
      x = 320
      y = 40
    }
  }

  action {
    id   = "prompt-fallback"
    next = "queue-by-attribute"
    message_participant {
      prompt_id = "prompt:welcome-prompt"
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
    position {
      x = 600
      y = 160
    }
  }

  action {
    id   = "queue-by-attribute"
    next = "hang-up"
    update_contact_target_queue {
      queue_id = "$.Attributes.queueId"
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
    position {
      x = 880
      y = 40
    }
  }

  action {
    id = "hang-up"
    disconnect_participant {}
    position {
      x = 1160
      y = 160
    }
  }
}
