# Generated by @flow-as-code/hcl from doc.flowdoc.json.
# Edits to structure regenerate; comments marked @keep survive.

resource "flowascode_contact_flow" "stored_input" {
  instance_id = var.connect_instance_id
  name        = "stored-input"
  type        = "CONTACT_FLOW"

  refs = {
    "prompt:callback-number" = data.aws_connect_prompt.callback_number.arn
  }

  action {
    id   = "ask-postcode"
    next = "ask-callback"
    get_participant_input {
      input_time_limit_seconds = 10
      input_validation = {
        custom_validation = {
          maximum_length = 5
        }
      }
      store_input = "True"
      text        = "Enter the five digit postcode of the address, then press pound."
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
  }

  action {
    id   = "ask-callback"
    next = "ask-international"
    get_participant_input {
      input_time_limit_seconds = 15
      input_validation = {
        phone_number_validation = {
          country_code  = "US"
          number_format = "Local"
        }
      }
      prompt_id   = "prompt:callback-number"
      store_input = "True"
    }
    error {
      type = "InvalidPhoneNumber"
      next = "bad-number"
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
  }

  action {
    id   = "bad-number"
    next = "ask-callback"
    message_participant {
      text = "That did not look like a phone number. Let us try again."
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
  }

  action {
    id   = "ask-international"
    next = "done"
    get_participant_input {
      input_time_limit_seconds = 15
      input_validation = {
        phone_number_validation = {
          number_format = "E164"
        }
      }
      ssml        = "<speak>Enter the number to reach you abroad, with the country code.</speak>"
      store_input = "True"
    }
    error {
      type = "InvalidPhoneNumber"
      next = "bad-number"
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
  }

  action {
    id   = "done"
    next = "bye"
    message_participant {
      text = "Thank you. We have what we need."
    }
    error {
      type = "NoMatchingError"
      next = "bye"
    }
  }

  action {
    id = "bye"
    disconnect_participant {}
  }
}
