// Generated by @flow-as-code/core codegen from default-queue-transfer.flowdoc.json.
// Edits to structure regenerate; comments marked @keep survive.

import {
  CheckMetricData,
  DisconnectParticipant,
  Flow,
  GenericBlock,
  MessageParticipant,
} from "@flow-as-code/core";

export function defaultQueueTransfer(): Flow {
  return new Flow({
    name: "default-queue-transfer",
    connectType: "QUEUE_TRANSFER",
    start: "1111aaaa-0000-4000-8000-000000000001",
    layout: {
      "1111aaaa-0000-4000-8000-000000000001": { x: 205, y: 127 },
      "1111aaaa-0000-4000-8000-000000000002": { x: 450, y: 297 },
      "1111aaaa-0000-4000-8000-000000000003": { x: 697, y: 229 },
      "1111aaaa-0000-4000-8000-000000000004": { x: 1328, y: 411 },
      "1111aaaa-0000-4000-8000-000000000005": { x: 1138, y: 232 },
      "1111aaaa-0000-4000-8000-000000000006": { x: 918, y: 37 },
      "1111aaaa-0000-4000-8000-000000000007": { x: 466.8238220214844, y: 26.44894027709961 },
      "1111aaaa-0000-4000-8000-000000000008": { x: 692, y: 40 },
    },
  }).add(
    new MessageParticipant({
      id: "1111aaaa-0000-4000-8000-000000000002",
      text: "We are currently out of hours. Goodbye.",
      next: "1111aaaa-0000-4000-8000-000000000004",
    }),
    new MessageParticipant({
      id: "1111aaaa-0000-4000-8000-000000000003",
      text: "There are currently no agents staffed. Goodbye.",
      next: "1111aaaa-0000-4000-8000-000000000004",
    }),
    new DisconnectParticipant({ id: "1111aaaa-0000-4000-8000-000000000004" }),
    new GenericBlock({
      id: "1111aaaa-0000-4000-8000-000000000001",
      type: "CheckHoursOfOperation",
      next: "1111aaaa-0000-4000-8000-000000000005",
      errors: [{ errorType: "NoMatchingError", target: "1111aaaa-0000-4000-8000-000000000005" }],
      conditions: [
        { target: "1111aaaa-0000-4000-8000-000000000007", operator: "Equals", operands: ["True"] },
        { target: "1111aaaa-0000-4000-8000-000000000002", operator: "Equals", operands: ["False"] },
      ],
    }),
    new MessageParticipant({
      id: "1111aaaa-0000-4000-8000-000000000005",
      text: "Failed to transfer to queue. Goodbye.",
      next: "1111aaaa-0000-4000-8000-000000000004",
    }),
    new GenericBlock({
      id: "1111aaaa-0000-4000-8000-000000000006",
      type: "TransferContactToQueue",
      next: "1111aaaa-0000-4000-8000-000000000005",
      errors: [
        { errorType: "NoMatchingError", target: "1111aaaa-0000-4000-8000-000000000005" },
        { errorType: "QueueAtCapacity", target: "1111aaaa-0000-4000-8000-000000000005" },
      ],
    }),
    new CheckMetricData({
      id: "1111aaaa-0000-4000-8000-000000000007",
      metric: "NumberOfAgentsStaffed",
      branches: [
        {
          operator: "NumberGreaterThan",
          operand: "0",
          target: "1111aaaa-0000-4000-8000-000000000008",
        },
      ],
      onNoMatch: "1111aaaa-0000-4000-8000-000000000003",
      onError: "1111aaaa-0000-4000-8000-000000000005",
    }),
    new MessageParticipant({
      id: "1111aaaa-0000-4000-8000-000000000008",
      text: "Now transferring.",
      next: "1111aaaa-0000-4000-8000-000000000006",
    }),
  );
}
