# Generated by @flow-as-code/hcl from minimal.flowdoc.json.
# Edits to structure regenerate; comments marked @keep survive.

# @keep Owned by the CX team.
# scratch note
resource "flowascode_contact_flow" "minimal" { # trailing comment
  // a slash comment
  /* a block
     comment */
  instance_id = var.connect_instance_id
  name        = "minimal"
  type        = "CONTACT_FLOW"

  refs = {
    "queue:appointments" = aws_connect_queue.appointments.arn
  }

  # @keep The greeting is legally reviewed text.
  # not kept
  action {
    id   = "welcome" # a trailing comment
    next = "set-queue"
    message_participant {
      text = "Welcome."
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
  }

  action {
    id   = "set-queue"
    next = "hang-up"
    update_contact_target_queue {
      queue_id = "queue:appointments"
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
  }

  action {
    id = "hang-up"
    disconnect_participant {}
  }
}
