# Generated by @flow-as-code/hcl from started.flowdoc.json.
# Edits to structure regenerate; comments marked @keep survive.

resource "flowascode_contact_flow" "started" {
  instance_id = var.connect_instance_id
  name        = "started"
  type        = "CONTACT_FLOW"
  start       = "welcome"

  action {
    id = "hang-up"
    disconnect_participant {}
  }

  action {
    id   = "welcome"
    next = "hang-up"
    message_participant {
      text = "Welcome."
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
  }
}
