# Generated by @flow-as-code/hcl from minimal.flowdoc.json.
# Edits to structure regenerate; comments marked @keep survive.

resource "flowascode_contact_flow" "minimal" {
  instance_id = var.connect_instance_id
  name        = "minimal"
  type        = "CONTACT_FLOW"

  action {
    id   = "welcome"
    next = "look-up"
    message_participant {
      text = "Welcome."
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
  }

  action {
    id   = "look-up"
    next = "look-up-again"
    invoke_lambda_function {
      invocation_time_limit_seconds = 8
      invocation_type               = "SYNCHRONOUS"
      lambda_function_arn           = aws_lambda_function.lookup.arn
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
  }

  action {
    id   = "look-up-again"
    next = "hang-up"
    invoke_lambda_function {
      invocation_time_limit_seconds = 8
      invocation_type               = "SYNCHRONOUS"
      lambda_function_arn           = data.aws_lambda_function.lookup.arn
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
  }

  action {
    id = "hang-up"
    disconnect_participant {}
  }
}
