# Generated by @flow-as-code/hcl from doc.flowdoc.json.
# Edits to structure regenerate; comments marked @keep survive.

resource "flowascode_contact_flow" "participant" {
  instance_id = var.connect_instance_id
  name        = "participant"
  type        = "CUSTOMER_QUEUE"
  description = "Participant actions in a customer queue flow."

  refs = {
    "lex:sales-bot"   = aws_lexv2models_bot_alias.sales_bot.arn
    "prompt:greeting" = aws_connect_prompt.greeting.arn
    # TODO: no terraform address for ${cdref:prompt:hold-music}.
    "prompt:hold-music" = null
    "view:form@1"       = data.flowascode_view.form.arn
  }

  action {
    id = "hold-music"
    message_participant_iteratively {
      interrupt_frequency_seconds = 30
      messages = [
        {
          text = "Thank you for holding."
        },
        {
          prompt_id = "prompt:hold-music"
        },
        {
          ssml = "<speak>An agent will be with you <break time=\"1s\"/> shortly.</speak>"
        },
        {
          media = {
            media_type  = "Audio"
            source_type = "S3"
            uri         = "s3://prompts/hold.wav"
          }
        },
      ]
    }
    condition {
      operator = "Equals"
      operands = ["MessagesInterrupted"]
      next     = "still-waiting"
    }
    error {
      type = "NoMatchingError"
      next = "hold-quietly"
    }
  }

  action {
    id   = "still-waiting"
    next = "ask-intent"
    message_participant {
      text = "Still waiting? An agent will be right with you."
    }
    error {
      type = "NoMatchingError"
      next = "end"
    }
  }

  action {
    id   = "ask-intent"
    next = "hold-quietly"
    connect_participant_with_lex_bot {
      lex_initialization_data = {
        initial_message = "Hi"
      }
      lex_session_attributes = {
        channel = "$.Channel"
      }
      lex_timeout_seconds = {
        text = 300
      }
      lex_v2_bot = {
        alias_arn = "lex:sales-bot"
      }
      text = "How can I help while you wait?"
    }
    condition {
      operator = "Equals"
      operands = ["Sales"]
      next     = "show-form"
    }
    condition {
      operator = "Equals"
      operands = ["Support"]
      next     = "show-any"
    }
    error {
      type = "InputTimeLimitExceeded"
      next = "end"
    }
    error {
      type = "NoMatchingError"
      next = "end"
    }
    error {
      type = "NoMatchingCondition"
      next = "hold-quietly"
    }
  }

  action {
    id   = "show-form"
    next = "end"
    show_view {
      invocation_time_limit_seconds = 300
      sensitive_data_configuration = {
        hide_response_on = ["TRANSCRIPT"]
      }
      view_data = jsonencode({
        Heading = "$.Customer.LastName"
        Sections = [
          {
            Title = "Address"
          },
        ]
      })
      view_resource = {
        id      = "view:form@1"
        version = "1"
      }
    }
    condition {
      operator = "Equals"
      operands = ["Next"]
      next     = "ask-again"
    }
    condition {
      operator = "Equals"
      operands = ["Back"]
      next     = "hold-music"
    }
    error {
      type = "NoMatchingCondition"
      next = "hold-quietly"
    }
    error {
      type = "NoMatchingError"
      next = "end"
    }
    error {
      type = "TimeLimitExceeded"
      next = "end"
    }
  }

  action {
    id   = "show-any"
    next = "end"
    show_view {
      invocation_time_limit_seconds = 300
      view_resource = {
        id = "$.Attributes.view"
      }
    }
    error {
      type = "NoMatchingCondition"
      next = "hold-quietly"
    }
    error {
      type = "NoMatchingError"
      next = "end"
    }
    error {
      type = "TimeLimitExceeded"
      next = "end"
    }
  }

  action {
    id   = "ask-again"
    next = "hold-music"
    connect_participant_with_lex_bot {
      lex_v2_bot = {
        alias_arn = "$.Attributes.botAlias"
      }
      prompt_id = "prompt:greeting"
    }
    error {
      type = "InputTimeLimitExceeded"
      next = "end"
    }
    error {
      type = "NoMatchingError"
      next = "end"
    }
    error {
      type = "NoMatchingCondition"
      next = "hold-music"
    }
  }

  action {
    id = "hold-quietly"
    message_participant_iteratively {
      messages = [
        {
          ssml = "<speak><break time=\"10s\"/></speak>"
        },
      ]
    }
  }

  action {
    id = "end"
    end_flow_execution {}
  }
}
