# Generated by @flow-as-code/hcl from prompted.flowdoc.json.
# Edits to structure regenerate; comments marked @keep survive.

resource "flowascode_contact_flow" "prompted" {
  instance_id = var.connect_instance_id
  name        = "prompted"
  type        = "CONTACT_FLOW"

  action {
    id   = "welcome"
    next = "hang-up"
    message_participant {
      prompt_id = data.aws_connect_prompt.welcome_prompt.arn
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
  }

  action {
    id = "hang-up"
    disconnect_participant {}
  }
}
