# Generated by @flow-as-code/hcl. Do not edit by hand: edit the
# FlowDocs and re-emit. See docs/06-terraform-provider.md.
#
# One resource per FlowDoc, applied by the flow-as-code/flowascode
# provider. Provider, credential, and backend configuration is yours;
# versions.tf.example lists what this needs.

resource "flowascode_contact_flow_module" "after_call_survey" {
  instance_id = var.connect_instance_id
  name        = "after-call-survey"

  refs = {
    "module:satisfaction-question@prod" = flowascode_contact_flow_module_alias.satisfaction_question_prod.arn
  }

  action {
    id   = "intro"
    next = "ask-question"
    message_participant {
      text = "Before you go, a one-question survey."
    }
    error {
      type = "NoMatchingError"
      next = "wrap-up"
    }
  }

  action {
    id   = "ask-question"
    next = "wrap-up"
    invoke_flow_module {
      flow_module_id = "module:satisfaction-question@prod"
    }
    error {
      type = "NoMatchingError"
      next = "wrap-up"
    }
  }

  action {
    id = "wrap-up"
    end_flow_module_execution {}
  }
}

# A snapshot of the module's content, replaced when the content
# changes, and the aliases it publishes: those the flows in this set
# invoke it through, and those declared to the emitter.
# Connect will not delete a version an alias points at, so the new
# version is created and the alias moved before the old one goes.
resource "flowascode_contact_flow_module_version" "after_call_survey" {
  instance_id            = var.connect_instance_id
  contact_flow_module_id = flowascode_contact_flow_module.after_call_survey.contact_flow_module_id
  content_hash           = flowascode_contact_flow_module.after_call_survey.content_hash

  lifecycle {
    create_before_destroy = true
  }
}

resource "flowascode_contact_flow_module_alias" "after_call_survey_prod" {
  instance_id                 = var.connect_instance_id
  contact_flow_module_id      = flowascode_contact_flow_module.after_call_survey.contact_flow_module_id
  name                        = "prod"
  contact_flow_module_version = flowascode_contact_flow_module_version.after_call_survey.version
}

resource "flowascode_contact_flow_module" "satisfaction_question" {
  instance_id = var.connect_instance_id
  name        = "satisfaction-question"

  action {
    id   = "ask"
    next = "done"
    get_participant_input {
      input_time_limit_seconds = 5
      store_input              = "False"
      text                     = "Press 1 if we solved your problem, or 2 if we did not."
    }
    condition {
      operator = "Equals"
      operands = ["1"]
      next     = "done"
    }
    condition {
      operator = "Equals"
      operands = ["2"]
      next     = "done"
    }
    error {
      type = "InputTimeLimitExceeded"
      next = "done"
    }
    error {
      type = "NoMatchingCondition"
      next = "done"
    }
    error {
      type = "NoMatchingError"
      next = "done"
    }
  }

  action {
    id = "done"
    end_flow_module_execution {}
  }
}

# A snapshot of the module's content, replaced when the content
# changes, and the aliases it publishes: those the flows in this set
# invoke it through, and those declared to the emitter.
# Connect will not delete a version an alias points at, so the new
# version is created and the alias moved before the old one goes.
resource "flowascode_contact_flow_module_version" "satisfaction_question" {
  instance_id            = var.connect_instance_id
  contact_flow_module_id = flowascode_contact_flow_module.satisfaction_question.contact_flow_module_id
  content_hash           = flowascode_contact_flow_module.satisfaction_question.content_hash

  lifecycle {
    create_before_destroy = true
  }
}

resource "flowascode_contact_flow_module_alias" "satisfaction_question_prod" {
  instance_id                 = var.connect_instance_id
  contact_flow_module_id      = flowascode_contact_flow_module.satisfaction_question.contact_flow_module_id
  name                        = "prod"
  contact_flow_module_version = flowascode_contact_flow_module_version.satisfaction_question.version
}

resource "flowascode_contact_flow" "support_line" {
  instance_id = var.connect_instance_id
  name        = "support-line"
  type        = "CONTACT_FLOW"

  refs = {
    "module:after-call-survey@prod" = flowascode_contact_flow_module_alias.after_call_survey_prod.arn
    "queue:appointments"            = aws_connect_queue.appointments.arn
  }

  action {
    id   = "welcome"
    next = "set-queue"
    message_participant {
      text = "Thanks for calling support."
    }
    error {
      type = "NoMatchingError"
      next = "survey"
    }
  }

  action {
    id   = "set-queue"
    next = "survey"
    update_contact_target_queue {
      queue_id = "queue:appointments"
    }
    error {
      type = "NoMatchingError"
      next = "survey"
    }
  }

  action {
    id   = "survey"
    next = "hang-up"
    invoke_flow_module {
      flow_module_id = "module:after-call-survey@prod"
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
  }

  action {
    id = "hang-up"
    disconnect_participant {}
  }
}
