# Generated by @flow-as-code/hcl. Do not edit by hand: edit the
# FlowDocs and re-emit. See docs/06-terraform-provider.md.

variable "connect_instance_id" {
  description = "Identifier of the Amazon Connect instance that holds these flows."
  type        = string
}
