// Generated by @flow-as-code/core codegen from customer-lookup.flowdoc.json.
// Edits to structure regenerate; comments marked @keep survive.

import { EndFlowModuleExecution, FlowModule, GenericBlock } from "@flow-as-code/core";

export function customerLookup(): FlowModule {
  return new FlowModule({
    name: "customer-lookup",
    settings: {
      InputParameters: [{ Name: "customerId", Required: true, Type: "String" }],
      OutputParameters: [],
      Transitions: [{ Description: "", DisplayName: "Success", ReferenceName: "Success" }],
    },
  }).add(
    new GenericBlock({
      id: "greet",
      type: "MessageParticipant",
      parameters: { Text: "One moment." },
      next: "end",
      errors: [{ errorType: "NoMatchingError", target: "end" }],
    }),
    new EndFlowModuleExecution({ id: "end" }),
  );
}
