# Generated by @flow-as-code/hcl from placed.flowdoc.json.
# Edits to structure regenerate; comments marked @keep survive.

resource "flowascode_contact_flow" "placed" {
  instance_id = var.connect_instance_id
  name        = "placed"
  type        = "CONTACT_FLOW"

  action {
    id   = "welcome"
    next = "hang-up"
    message_participant {
      text = "Welcome."
    }
    error {
      type = "NoMatchingError"
      next = "hang-up"
    }
    position {
      x = 100
      y = 200
    }
  }

  action {
    id = "hang-up"
    disconnect_participant {}
  }
}
